server:
  port: 8082

spring:
  application:
    name: portfolio-service
  data:
    mongodb:
      uri: mongodb+srv://<your-mongo-user>:<your-mongo-password>@cluster0.mongodb.net/financial_advisor?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # Prevents deserialization issues in other services

kafka:
  topic:
    portfolio-analysis: portfolio-analysis-events